default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: workshops
  password: pass1234

development:
  <<: *default
  database: fight_club_development


test:
  <<: *default
  database: fight_club_test

production:
  <<: *default
  database: fight_club_production
  username: fight_club
  password: <%= ENV['CAR-RENTAL_DATABASE_PASSWORD'] %>
